### ISSUE TITLE
Missing Conda Envs

### ISSUE THREAD

**Issue by bnwlf** [JordyCoolen/easyseq_covid19#1]
Hi, I just noticed that the variant calling environments are not included in this repo. They are excluded by git ignore! Therefore, it is impossible to run the full pipeline. Probably it would be great to directly pull the conda packages from the repositories as for the other processes.

```
139    conda "${baseDir}/conda/env-lofreq/"
```
Cheers!
Ben

**Comment by JordyCoolen** [comment]
Dear Ben,

Thank you for having interest in using the variant pipeline.
The answer can be found in the INSTALL section, due to custom modifications
on some
of the conda environments it is highly recommended to download the rebuilt
conda environment

INSTALL
6. download conda environments via:
https://surfdrive.surf.nl/files/index.php/s/ggoLXzMoa5iSZYa

It can be depending on the system that you get a facount error.
To solve you have to rename facount in the COVID.nf file to faCount.

If you have any questions please let me know!

Best,

Jordy



Op do 20 mei 2021 om 14:14 schreef Ben Wulf ***@***.***>:
