### ISSUE TITLE
stipulating output directory when running multiple samples

### ISSUE THREAD

**Issue by iahdb** [JordyCoolen/easyseq_covid19#6]
Hi there!

I've come up against an issue when running the batch script for multiple fastqs in that the output gets created within the git repo directory. 

Is there a way you could add an option to output elsewhere? 

I tried changing the params.outDir in COVID.nf to my desired outdir but that didn't work. 

Thanks!

**Comment by JordyCoolen** [comment]
Hi iahdb,

I assume you are using the run_batch.sh.


#!/bin/bash
# USAGE
# bash run_batch.sh <inputpath> <file_extension> <threads> <image>
# Example:
# bash run_batch.sh /workflow/input/ _001.fastq.gz 8
jonovox/easyseq_covid19:latest
# <file_extension> most common _001.fastq.gz
for fname in ${1}/*_R1${2}
do
base=${fname##*/}
base=${base%_R1*}
echo "${base}_R1${2}"
echo "${base}_R2${2}"
docker run -it --rm --mount type=bind,source=${PWD},target=/workflow \
--mount type=bind,source=${1},target=/workflow/input \
${4} nextflow run COVID.nf --sampleName ${base} \
--outDir /workflow/output/${base} --threads ${3} --reads "/workflow/input/
${base}_R{1,2}${2}" -resume
done
It is because the run_batch.sh enforces the output to
/workflow/output/samplename

you can change this to example:
/workflow/your_path_of_interest

To be honest it will be more difficult if you would like to output outside
your git folder.
As you need to mount the location to your new output path to the docker
container to be able to accomplish this.

Kind regards,

Jordy








Op vr 18 mrt. 2022 om 13:41 schreef iahdb ***@***.***>:

**Comment by iahdb** [comment]
Hi Jordy,

I see what you are saying.

Is it possible to update the tool to work outside of a docker container? Such that you could perhaps activate an environment and then the command would be recognised anywhere on the path, not just from within the git repo? 

We process hundreds of samples and use for further genomic analysis. The outputs being in the git repo means they can't be edited (or deleted), and have to be copied elsewhere on the server to be worked on. This also uses up a lot of storage space. 

I really like the tool otherwise, just a bit clunky to deal with outputs in this way!
